# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-11 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file_name',
            field=models.FileField(upload_to='Files/'),
        ),
    ]
